### ISSUE TITLE
Consider adding macros for common HTTP methods

### ISSUE THREAD

**Issue by fwgreen** [Star-Lord-PHB/VaporController#1]
Thanks for creating this!  This project is a great idea and will help people coming from frameworks such as Spring or Asp.Net move to Vapor.  With that idea in mind, please consider also adding macros for the common HTTP methods as an option.
```Swift
//something like...
@HttpGet(path: "hello", ":firstName", ":lastName") 
//as an alternative to...
@EndPoint(method: .GET, path: "hello", ":firstName", ":lastName") 
```
The recognizability might also aid those making the pitch for adopting Vapor in places.

**Comment by Star-Lord-PHB** [comment]
Added in version 1.3.0 (0d18180), please give it a try

**Comment by fwgreen** [comment]
Thank you and thanks for all your hard work!
